Changed config files management
kogitoapp/puppet-kapacitor pull request #3
Opened 2022-01-13 12:19 UTC by CatInCosmicSpace

Hello! 

Slightly changed the formatting for all manifests. 

Main change: a different approach to configuration file and service management. 
If the Kapacitor should be `'absent'`, then the configuration and service files should also be `'absent'`. Also service should not be `running`. Otherwise, the previously existing parameters `*_manage` are used.

Best regards,
Alena.

2022-01-13 14:34 UTC, ZloeSabo requested changes
Hey @CatInCosmicSpace, thank you for the contribution. I've added some comments. Please don't hesitate to ask me

2022-01-13 15:24 UTC, CatInCosmicSpace commented on manifests/config.pp
> +    force  => true,
`force` is needed to completely delete the configuration directory. Otherwise, puppet would not remove directory if there any other files inside.

2022-01-13 15:35 UTC, CatInCosmicSpace commented on manifests/config.pp
> +class kapacitor::config inherits kapacitor {
1. I decided to use inheritance here, since all parameters in general are inherited from the default parameters, and they can already be redefined in the `kapacitor` or `kapacitor::params` class.
2. Ok, that makes sense. I revert the parameters change.

2022-01-13 15:43 UTC, CatInCosmicSpace commented on manifests/init.pp
> +  Boolean $manage_repo                             = true,
1. Sorry. I thought it would look better this way.
2. Ok, reverted formatting.

2022-01-13 15:49 UTC, CatInCosmicSpace commented on manifests/service.pp
> +  if $manage_service and $kapacitor::ensure != 'absent' {
Done.

2022-01-13 16:02 UTC, CatInCosmicSpace commented on manifests/config.pp
> +class kapacitor::config inherits kapacitor {
If I understood correctly, then I did. If not, please explain about the parameter. I thought about this method and about adding something like boolean `manage_config`.

2022-01-13 16:03 UTC, CatInCosmicSpace commented
Please do a review.

2022-01-14 09:09 UTC, CatInCosmicSpace commented
I would also like to ask if it is worth adding some defined types to install, for example, scripts from the puppet? Something like 
[`chronograf::connection::influx`](https://github.com/kogitoapp/puppet-chronograf/blob/8014da8d035cd35061728c336eb57d6eb877d5ca/manifests/connection/influx.pp#L5) or [`chronograf::connection::kapacitor`](https://github.com/kogitoapp/puppet-chronograf/blob/8014da8d035cd35061728c336eb57d6eb877d5ca/manifests/connection/kapacitor.pp#L5) in [`puppet-chronograf`](https://github.com/kogitoapp/puppet-chronograf) repo.

2022-01-17 10:50 UTC, ZloeSabo commented
Thank you @CatInCosmicSpace, it's a great job. I'm merging it now.

As for defines, it's your call whether to do it or not. We did not have a use case for them, so we did not add them. If you need such functionality, please feel free to put together a PR.

2022-01-17 10:50 UTC, merged